version: 2.1
jobs:
  deploy:
    docker:
      - image: cimg/node:18.10.0
    steps:
      - add_ssh_keys:
          fingerprints:
            - SHA256:jkdeI39yesOQufOjax6gxGmEs5WkwPNe6LrfraeQWhw
      - run:
          name: Deploy Over SSH
          command: |
            ssh -t ubuntu@3.15.24.7	 <<-'ENDSSH'
              pwd
            ENDSSH
